### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [9]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1, 5]

13

In [12]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

4

In [18]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [19]:
# replace 
b[:,1,:] = [[9,9],[8,8]] # [[9,9,9],[8,8]] gives error

In [20]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [24]:
# Any other number
np.full((2,2), 99, dtype='float32') # 99 can be changed

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [25]:
# Any other number (full_like) allows us to take a shape we have already built, in this case, a.
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
np.random.rand(4,2) 

array([[0.48557611, 0.37810353],
       [0.29844895, 0.45500255],
       [0.40775266, 0.25568315],
       [0.14804941, 0.55455131]])

In [27]:
np.random.rand(4,2,3) # can be more complicated

array([[[0.13273417, 0.63705492, 0.3739433 ],
        [0.44810815, 0.0645601 , 0.47322027]],

       [[0.36804547, 0.256089  , 0.1678596 ],
        [0.79752805, 0.80019985, 0.70581398]],

       [[0.67880884, 0.32336023, 0.5970039 ],
        [0.76903959, 0.37534393, 0.37066711]],

       [[0.63601322, 0.08146094, 0.28287957],
        [0.45668319, 0.67528952, 0.75677865]]])

In [28]:
np.random.random_sample(a.shape) # another method

array([[0.45138721, 0.64530184, 0.26185295, 0.65985922, 0.45306495,
        0.99027621, 0.83077775],
       [0.46074101, 0.48619233, 0.93150278, 0.30662261, 0.71638815,
        0.28987101, 0.629455  ]])

In [29]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) 
# means -4 to 7 excludes 8

array([[ 3,  7, -3],
       [-4,  2, -2],
       [ 1, -3,  0]])

In [30]:
# The identity matrix (square matrix)
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [31]:
# Repeat an array
arr = np.array([[1,2,3]]) # 2d array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [32]:
# My answer is ...
F1 = np.ones((5,5))
print(F1)
F2 = np.zeros((3,3))
F2[1,1]= 9
print(F2)
F1[1:4,1:4] = F2
print(F1)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [33]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [34]:
a = np.array([1,2,3])
b = a.copy() # cannot just say b = a
b[0] = 100

print(a)

[1 2 3]


### Mathematics

In [35]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [36]:
a + 2

array([3, 4, 5, 6])

In [37]:
a - 2

array([-1,  0,  1,  2])

In [38]:
a * 2

array([2, 4, 6, 8])

In [39]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [40]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [41]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [42]:
# Take the sin
np.sin(a)



array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [43]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [44]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2) # for twos and onwards
print(b)

# a*b does not work

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [45]:
# Find the determinant
c = np.identity(3) 
print(c)
np.linalg.det(c) # determinant

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [46]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [47]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.min(stats)

1

In [49]:
np.min(stats, axis=1)

array([1, 4])

In [50]:
np.min(stats, axis=0)

array([1, 2, 3])

In [51]:
np.max(stats, axis=1) # axis=1 means along row -->

array([3, 6])

In [52]:
np.sum(stats, axis=0) # axis=0 means down the column 

array([5, 7, 9])

### Reorganizing Arrays

In [56]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)


print(''' 

''')


after = before.reshape((4,2))
print(after)


print(''' 

''')


after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
 


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
 


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [57]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [61]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [62]:
(~((filedata > 50) & (filedata < 100))) # ~ means not

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [63]:
## YOu can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [64]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [65]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])